version: '2.3'

services:
  elyra:
    build:
      context: .
      dockerfile: ./elyra/elyra.Dockerfile
    image: elyra/jupyter:latest
    container_name: elyra_jupyter
    env_file:
      - .env
    environment:
      - portz:8888
    volumes:
      - ./temp:/jovyan/temp
      - ../pipelines:/jovyan/pipelines:ro
    entrypoint: "bash -c 'jupyter lab --no-browser --ip=0.0.0.0 --port=8879 --allow-root --NotebookApp.password=${notebook_pw}'"
    ports:
      - "${notebook_ip:-0.0.0.0}:${notebook_port:-8888}:8879"