version: '2.3'

services:
  elyra:
    build:
      context: .
      dockerfile: ./elyra/elyra.Dockerfile
    image: elyra/jupyter:latest
    container_name: elyra_jupyter
    environment:
      PYTHONPATH: /art_pipelines
      config_path: /home/jovyan/config.yaml
    volumes:
      - ${input_dir:-./temp/inputs}:/inputs/:ro
      - ${output_dir:-./outputs/}:/outputs/
      - ./temp:/home/jovyan/temp
      - ./art_pipelines/:/art_pipelines:ro
      - ${local_config_path:-./art_pipelines/configs/config.yaml}:/home/jovyan/config.yaml:ro
    entrypoint: "bash -c 'jupyter lab --no-browser --ip=0.0.0.0 --port=8879 --allow-root --NotebookApp.password=${notebook_pw}'"
    ports:
      - "${notebook_ip:-0.0.0.0}:${notebook_port:-8888}:8879"
  fastapi:
    build:
      context: .
      dockerfile: ./server/server.Dockerfile
    #image: pytorch/pytorch:latest
    container_name: fastapi
    environment:
      PYTHONPATH: /art_pipelines
    volumes:
      - ./art_pipelines/:/art_pipelines:ro
      - ./server/:/workspace/server:ro
    #entrypoint: "dir ./"
    entrypoint: "uvicorn server.main:app --reload"
    ports:
      - "8000:8000"