pipelines:
  - pipeline:
    input_dir: ../temp/outputs/
    name: vr_distort
    include_types: [mp4]
    to_type: mp4
    k1: 0.3358  # negative to remove barrel distortion
    k2: 0.5534
    p1: 0  # -.001#-.005;
    p2: 0  # -.001#.01;
    focal_length_x: 500.
    focal_length_y: 500.
    output_dir: ../temp/outputs/video_1